<?php

/**
 * This file is part of the dinThemePlugin package.
 * (c) DineCat, 2010 http://dinecat.com/
 * 
 * For the full copyright and license information, please view the LICENSE file,
 * that was distributed with this package, or see http://www.dinecat.com/din/license.html
 */

/**
 * Class for handle theme general configuration
 * 
 * @package     dinThemePlugin
 * @subpackage  lib.config
 * @author      Nicolay N. Zyk <relo.san@gmail.com>
 */
class dinThemeConfigHandler extends sfYamlConfigHandler
{

    /**
     * Create PHP code with theme config data for cache
     * 
     * @param   array   $configFiles    Array with configuration files path's
     * @return  string  Generated PHP code with config data for cache
     */
    public function execute( $configFiles )
    {

        $config = self::parseYamls( $configFiles );

        $data = array();
        if ( $config )
        {
            $data[] = "switch ( sfConfig::get( 'app_view_theme', 'default' ) )\n{";
            foreach ( $config as $theme => $param )
            {
                $data[] = "    case '" . $theme . "':";
                $data[] = "        sfConfig::set( 'theme_" . $theme . "_path', '"
                        . $param['theme_path'] . "' );";
                $data[] = "        sfConfig::set( 'theme_" . $theme . "_layout_path', '"
                        . $param['layout_path'] . "' );";
                $data[] = "        sfConfig::set( 'theme_" . $theme . "_module_path', '"
                        . $param['modules_path'] . "' );";
                $data[] = '        break;';
            }
            $data[] = "}\n";
        }

        return  sprintf(
            '<' . "?php\n\n// auto-generated by dinThemeConfigHandler\n// date: %s\n\n%s\n//EOF",
            date( 'Y/m/d H:i:s' ), implode( "\n", $data )
        );

    } // dinThemeConfigHandler::execute()

} // dinThemeConfigHandler

//EOF